apiVersion: v1
kind: Service
metadata: 
  labels:
    app: bookapi
  name: bookapi-service
  namespace: default
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: bookapi
  type: ClusterIP